[default]
timeout = 300
#waitUntil = "load"
waitUntil = "networkidle"

[cqgkld]
title = "重庆市公考雷达"
url = "https://www.gongkaoleida.com/area/2460-2461-0-2,3,59,78-124"
entrySelector = "body > section > div.mdn-content-box.clearfix > div > div"
titleSelector = ".notice-list > ul > li > h5"
linkSelector = ".notice-list > ul > li > h5 > a"
dateSelector = ".date"
dateFormat = "yyyy-MM-dd"

[cqsydw]
title = "重庆市人社局-事业单位公开招聘"
url = "https://rlsbj.cq.gov.cn/zwxx_182/sydw/"
entrySelector = "body > div.page-list.clearfix"
titleSelector = "ul.tab-item > li"
linkSelector = "ul.tab-item > li > a"
dateSelector = "ul.tab-item > li > span"
dateFormat = "yyyy-MM-dd"
