[default]
timeout = 300
#waitUntil = "load"
waitUntil = "networkidle"

[cqgkld]
title = "重庆市公考雷达"
url = "https://www.gongkaoleida.com/area/2460-2461-0-2,3,59,78-124"
entrySelector = "link-list"
titleSelector = "h5 a"
linkSelector = "h5 a"
dateSelector = " time-red "
dateFormat = "yyyy-MM-dd"

[cqsydw]
title = "重庆市人社局-事业单位公开招聘"
url = "https://rlsbj.cq.gov.cn/zwxx_182/sydw/sydwgkzp2026/"
entrySelector = "rsj-list1"
titleSelector = "li"
linkSelector = "a"
dateSelector = "span"
dateFormat = "yyyy-MM-dd"

[cqsydwjqtks]
title = "重庆市人社局-事业单位及其他考试"
url = "https://rlsbj.cq.gov.cn/ywzl/rsks/sydwks/"
entrySelector = ".rsj-list1"
titleSelector = "li a"
linkSelector = "li a"
dateSelector = "li span"
dateFormat = "yyyy-MM-dd"

[cqgwy]
title = "重庆市人社局-公务员考试"
url = "https://rlsbj.cq.gov.cn/ywzl/rsks/gwyks/"
entrySelector = ".rsj-list1"
titleSelector = "li a"
linkSelector = "li a"
dateSelector = "li span"
dateFormat = "yyyy-MM-dd"

[cqshhfwks]
title = "重庆市人社局-社会化服务考试"
url = "https://rlsbj.cq.gov.cn/ywzl/rsks/shhfw/"
entrySelector = ".rsj-list1"
titleSelector = "li a"
linkSelector = "li a"
dateSelector = "li span"
dateFormat = "yyyy-MM-dd"

[cqgsxx]
title = "重庆市人社局-公示信息"
url = "https://rlsbj.cq.gov.cn/zwxx_182/gsxx/"
entrySelector = ".rsj-list1"
titleSelector = "li a"
linkSelector = "li a"
dateSelector = "li span"
dateFormat = "yyyy-MM-dd"

[cqgqzp]
title = "重庆市国资委国企招聘页面"
url = "http://gzw.cq.gov.cn/gqzp/"
entrySelector = "tab-item"
titleSelector = "li a"
linkSelector = "li a"
dateSelector = "li span"
dateFormat = "yyyy-MM-dd"

[cqfenbi]
title = "重庆粉笔招考"
url = "https://www.fenbi.com/page/fenxiaozhaokao/25"
entrySelector = ".zhaokaoxinxi-item ng-star-inserted"
titleSelector = "a div"
linkSelector = "div a"

[jinbiaochi]
title = "金标尺重庆教师工作相关页面"
url = "https://cq.jinbiaochi.com/jsgz/column_114/"
entrySelector = "jbc_lists" 
titleSelector = "li a" 
linkSelector = "a" 
dateSelector = "span" 
dateFormat = "yyyy-MM-dd" 

[readblog]
title = "读书博客"
url = "https://bf.zzxworld.com/s/diligent_list"
entrySelector = "ppatiem_lit ppatiem_aitms"
titleSelector = "li"
linkSelector = "a"
dateSelector = "time"
dateFormat = "yyyy-MM-dd"
